version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/shell.html
  upload: static/shell.html 

- url: /.*
  script: chafagram.app
